# 全局异常处理
zeta-java项目提供了两个自定义异常`ArgumentException(参数异常)`、`BusinessException(业务异常)`。

它们分别用于请求参数校验出错，业务执行出错的时候。

使用方式很简单，手动抛出一个异常：
```java
throw new BusinessException("因为xxx原因，业务进行不下去了，请管理员检查");
```
手动抛出的异常会被全局异常处理器拦截并处理自动将异常转换成一个请求失败的返回值。



## 定义一个自定义的异常

很多时候，仅仅靠本项目提供的这两个自定义异常是远远不够的，因为异常粒度太粗了。

如果业务需要细粒度的异常码以及异常描述，我们可以选择自己仿照着写一个属于自己的自定义异常。

**第一步：**

定义好我们自定义异常的异常码，以及默认异常描述

ErrorCodeEnum.kt

```java
/**
 * 异常枚举
 *
 * @author gcc
 */
public enum ErrorCodeEnum {
    // ...其它的异常码
    
    /***************************自定义错误******************************/
    /** 文件上传失败 */
    ERR_FILE_UPLOAD_FAIL(8888, "文件上传失败")
    ;

    /** 错误码 */
    private final int code;
    /** 错误描述 */
    private final String msg;

    ErrorCodeEnum(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public int getCode() {
        return code;
    }

    public String getMsg() {
        return msg;
    }
}
```

**第二步：**

编写自定义异常

FileUploadFailException.java

```java
/**
 * 文件上传失败异常
 * 
 * 说明：
 * 自定义异常
 * @author gcc
 */
public class  FileUploadFailException extends RuntimeException {

    /** 异常编码 */
    private Integer code = ErrorCodeEnum.ERR_FILE_UPLOAD_FAIL.getCode();

    public BusinessException() {
        super(ErrorCodeEnum.ERR_FILE_UPLOAD_FAIL.getMsg());
    }

    public BusinessException(String message) {
        super(message);
    }

    public BusinessException(Integer code, String message) {
        super(message);
        this.code = code;
    }

    public BusinessException(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException(Throwable cause) {
        super(cause);
    }

    public BusinessException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

}
```

**第三步：**

全局异常处理器中拦截并处理该异常

GlobalExceptionHandler.java

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 全局异常处理器
 *
 * @author gcc
 */
@RestControllerAdvice
public class GlobalExceptionHandler {
    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    // ....其它的异常处理

    /**
     * 文件上传失败异常处理
     */
    @ExceptionHandler(FileUploadFailException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ApiResult<?> argumentExceptionHandler(FileUploadFailException ex) {
        logger.error("抛出文件上传失败异常：", ex);
        return ApiResult.result(ex.getCode(), ex.getMessage(), null);
    }
}
```



## 使用自定义的异常

自定义异常写完了，使用一下看看吧

SysFileController.java
```java
@Api(tags = "系统文件")
@PreAuth(replace = "sys:file")
@RestController
@RequestMapping("/api/system/file")
public class SysFileController extends SuperSimpleController<ISysFileService, SysFile> {


    /**
     * 测试触发自定义异常
     */
    @GetMapping("/test")
    public ApiResult<Boolean> testThrowException() {
        throw new FileUploadFailException("哎呀呀，文件上传失败了~~ 可能网络不好，请稍后再试");
    }

}
```

请求接口返回的结果为：
```json
{
  "code": 8888,
  "message": "哎呀呀，文件上传失败了~~ 可能网络不好，请稍后再试",
  "data": null,
  "error": null
}
```
